/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author ahmd.maulidanngmail.com
 */
public class stateBosan extends javax.swing.JFrame {

    /**
     * Creates new form stateBosan
     */
    public stateBosan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        makan = new javax.swing.JButton();
        main = new javax.swing.JButton();
        istirahat = new javax.swing.JButton();
        nyatakan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        makan.setText("Ajak Makan");
        makan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanActionPerformed(evt);
            }
        });
        getContentPane().add(makan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 106, 37));

        main.setText("Ajak Main");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 106, 37));

        istirahat.setText("Ajak Istirahat");
        istirahat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istirahatActionPerformed(evt);
            }
        });
        getContentPane().add(istirahat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 106, 37));

        nyatakan.setText("Nyatakan Perasaan");
        nyatakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyatakanActionPerformed(evt);
            }
        });
        getContentPane().add(nyatakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 150, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/bosan.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        // TODO add your handling code here:
        this.dispose();
        stateHappy sh = new stateHappy();
        sh.setVisible(true);
        sh.pack();
        sh.setLocationRelativeTo(null);
        sh.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_mainActionPerformed

    private void makanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        stateBosan sb = new stateBosan();
        sb.setVisible(true);
        sb.pack();
        sb.setLocationRelativeTo(null);
        sb.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_makanActionPerformed

    private void istirahatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istirahatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        stateBosan sb = new stateBosan();
        sb.setVisible(true);
        sb.pack();
        sb.setLocationRelativeTo(null);
        sb.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_istirahatActionPerformed

    private void nyatakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyatakanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        stateDitolak sk = new stateDitolak();
        sk.setVisible(true);
        sk.pack();
        sk.setLocationRelativeTo(null);
        sk.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_nyatakanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stateBosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stateBosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stateBosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stateBosan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stateBosan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton istirahat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton main;
    private javax.swing.JButton makan;
    private javax.swing.JButton nyatakan;
    // End of variables declaration//GEN-END:variables
}
